### ISSUE TITLE
Error running command cblite.explorer.getDocument

### ISSUE THREAD

**Issue by tele-bird** [couchbaselabs/vscode-cblite#12]
Using this sample app, I wrote data to the CBLite database on my iPhone simulator running on my Mac:

https://developer.couchbase.com/tutorial-quickstart-xamarin-forms-basic

I'm able to install the CBLite extension into my VSCode, open a cblite2 database, and the data appears in the left pane in VSCode (but only after re-opening the folder and database).  However, when I right-click the DB file and select GetDocument, I get the following error:

![Screenshot 2024-10-02 at 10 02 46 AM](https://github.com/user-attachments/assets/9383ec1c-f5f8-4770-8141-6dc04c394e16)

**Comment by Benjelino** [comment]
@tele-bird is this issue resolved, I am facing this same issue

**Comment by tele-bird** [comment]
I tried again in this other sample app, and it still happens with the "user-profile" database.
https://developer.couchbase.com/tutorial-quickstart-xamarin-forms-query
However, I notice that the issue does **not** happen for documents in the "universities" database in this sample app.  Probably there is something materially different in the "user-profile" database that is causing the issue.  There may be a problem in those example apps, but I think that the cblite extension could handle the problem more gracefully.

**Comment by borrrden** [comment]
This is actually the result of upgrading the database to 3.2.0 format.  There was a breaking change in the binary format that makes it unreadable on 3.1.x.  This should get resolved with an update to use the 3.2.0 SDK via the plugin.

**Comment by tele-bird** [comment]
@borrrden  I am currently using version 3.2.0 of the Couchbase.Lite library but I'm still seeing this issue.  I delete the data file, and it gets created using version 3.2.0, so there should be no legacy issues, correct?

here's my VS Code version

Version: 1.95.1 (Universal)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

And my version of the plugin is v0.2.0

**Comment by borrrden** [comment]
That's exactly WHY you see the issue.  The latest version of the plugin does NOT use 3.2.0.  I guess I could have been clearer about that (the plugin is still on an older version and there was a break that causes newer versions to be unable to be read).  I think this was actually fixed in 3.2.1 which is on its way out the door so if you use that let me know what happens in lieu of this plugin getting updated.

**Comment by tele-bird** [comment]
@borrrden  Thanks for clarifying.  I'll upgrade our SDK to 3.2.1 as soon as it is released and re-test the VS Code plugin.

**Comment by tele-bird** [comment]
I want to try the fix!  
@bmeike , what version of the VS Code plugin will this fix make it into?
